seed = 0
function = "bin.model.main"
n_trials = 50
sampler = { n_startup_trials = 15 }

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/california"
num_policy = "noisy-quantile"

[space.optimizer]
type = "AdamW"
lr = ["_tune_", "loguniform", 1e-4, 5e-3]
weight_decay = ["_tune_", "loguniform", 1e-5, 1e-1]

[space.model]
arch_type = "tabm-lora"
k = 32
rank = 8
lora_alpha = 0.5
share_training_batches = false

[space.model.backbone]
type = "MLP"
n_blocks = 3
d_block = 400
dropout = 0.20769705860329654
